CREATE TABLE
	"USER_CREDENTIALS" (
		"USER_ID" VARCHAR2 (40 BYTE) NOT NULL ENABLE,
		"PASSWORD" VARCHAR2 (20 BYTE) NOT NULL ENABLE,
		"ROLE_ID" VARCHAR2 (20 BYTE) NOT NULL ENABLE,
		"TOKEN" VARCHAR2 (80 BYTE),
		"EXPIRATION_TIME" LONG,
		CONSTRAINT "USER_CREDENTIALS_PK" PRIMARY KEY ("USER_ID") ENABLE
	);

CREATE TABLE
	"CUSTOMERS" (
		"CUSTOMER_ID" VARCHAR2 (12 BYTE) NOT NULL ENABLE,
		"CUSTOMER_NAME" VARCHAR2 (40 BYTE),
		"GENDER" VARCHAR2 (40 BYTE),
		"PHONE_NO" VARCHAR2 (20 BYTE),
		"EMAIL_ID" VARCHAR2 (40 BYTE),
		CONSTRAINT "CUSTOMER_PK" PRIMARY KEY ("CUSTOMER_ID") ENABLE,
		CONSTRAINT "UNIQUE_EMAIL" UNIQUE ("EMAIL_ID") ENABLE
	);

CREATE TABLE
	"LOANS" (
		"LOAN_ID" NUMBER NOT NULL ENABLE,
		"LOAN_TYPE" VARCHAR2 (20 BYTE) NOT NULL ENABLE,
		"DESCRIPTION" VARCHAR2 (40 BYTE),
		"INTEREST_RATE" NUMBER (4, 2),
		CONSTRAINT "LOAN_PK" PRIMARY KEY ("LOAN_ID") ENABLE
	);

CREATE TABLE
	"LOAN_APPLICATIONS" (
		"APPLICATION_ID" VARCHAR2 (15 BYTE) NOT NULL ENABLE,
		"CUSTOMER_ID" VARCHAR2 (12 BYTE) NOT NULL ENABLE,
		"LOAN_ID" NUMBER NOT NULL ENABLE,
		"LOAN_AMOUNT" NUMBER (*, 2) NOT NULL ENABLE,
		"TENURE" NUMBER NOT NULL ENABLE,
		"APPLICATION_DATE" DATE NOT NULL ENABLE,
		"APPLICATION_STATUS" VARCHAR2 (20 BYTE),
		"REMARKS" VARCHAR2 (20 BYTE),
		"INTEREST_RATE" NUMBER (4, 2) NOT NULL ENABLE,
		"DOCUMENT_ONE" BLOB,
		"DOCUMENT_TWO" BLOB,
		CONSTRAINT "LOAN_APPLICATION_PK" PRIMARY KEY ("APPLICATION_ID"),
		CONSTRAINT "LOAN_PK_FK" FOREIGN KEY ("LOAN_ID") REFERENCES "LOANS" ("LOAN_ID") ENABLE,
		CONSTRAINT "CUSTOMER_PK_FK" FOREIGN KEY ("CUSTOMER_ID") REFERENCES "CUSTOMERS" ("CUSTOMER_ID") ENABLE
	);